### PR TITLE
Add testing, UI updating, and bug fixing

### LINKED ISSUE #11: As a student, I want to be able to see the pre-requisite modules of a module so that I can see what modules to take.

### PR DESCRIPTION
**Pull request by hzf1174**
Testing
- Add system test for
`addModuleS`
`addModuleT`
`removeModuleS`
`removeModuleT`
`search`

- Add other tests
`showModuleParser`
`ModsUniParser`

- Miscellaneous related to testing

1. add a test `student` for testing(convenient for login)
2. add more modules in sample data

- UI update
1. remove `description` and add "MCs" after `credit` in `ModuleCard`
2. remove `lockedModule` and add `prerequisite` in `ModuleDisplay`

- Bug fixed

1. Validation of `Code`
2. Browser load default page in stead of `null` after `MainWindowClearResourceEvent`

Resolves #11

This PR is the last for my code part.

### CODE REVIEW

File: src/main/java/seedu/modsuni/logic/PrereqGenerator.java [hunk 1]
```diff
@@ -215,7 +215,7 @@ private static void checkCodePosition(char current, char prev, StringBuilder bui
     private static void checkCommaPosition(char current, char prev, StringBuilder builder) throws ParseException {
         if (current == ',' && (prev == '&' || prev == '|' || prev == ',' || prev == '(' || prev == ')')) {
             throw new ParseException(MESSAGE_COMMA_WRONG_POSITION);
-        } else {
+        } else if (current == ',') {
```
Comment (CrimsonJacket) [inline src/main/java/seedu/modsuni/logic/PrereqGenerator.java]: consider changing this 'magic-number ' variable

File: src/test/java/guitests/guihandles/MainWindowHandle.java [hunk 2]
```diff
@@ -7,27 +7,40 @@
...
     public MainWindowHandle(Stage stage) {
         super(stage);
 
-        moduleListPanel = new ModuleListPanelHandle(getChildNode(ModuleListPanelHandle.MODULE_LIST_VIEW_ID));
+        stagedModuleListPanel = new StagedModuleListPanelHandle(
+                getChildNode(StagedModuleListPanelHandle.MODULE_LIST_VIEW_ID));
+        takenModuleListPanel = new TakenModuleListPanelHandle(
+                getChildNode(TakenModuleListPanelHandle.MODULE_LIST_VIEW_ID));
+        databaseModuleListPanel = new DatabaseModuleListPanelHandle(
+                getChildNode(DatabaseModuleListPanelHandle.MODULE_LIST_VIEW_ID));
```
Comment (CrimsonJacket) [inline src/test/java/guitests/guihandles/MainWindowHandle.java]: Good job including GUI handles for the respective UI elements

File: src/test/java/seedu/modsuni/logic/parser/ModsUniParserTest.java [hunk 3]
```diff
@@ -76,6 +87,53 @@ public void parseCommand_add() throws Exception {
...
+        assertEquals(new SearchCommand(new CodeStartsKeywordsPredicate(keywords)), command);
+    }
+
+    @Test
+    public void parseCommand_showModule() throws Exception {
+        ShowModuleCommand command = (ShowModuleCommand) parser
+                .parseCommand(ShowModuleCommand.COMMAND_WORD + CODE_DESC_ACC1002);
+        assertEquals(new ShowModuleCommand(new Code("ACC1002")), command);
+    }
+
```
Comment (CrimsonJacket) [inline src/test/java/seedu/modsuni/logic/parser/ModsUniParserTest.java]: Good work including so all these test cases :+1:
