### PR TITLE
Admin Management: AddModuleToDatabaseCommand & test cases for Admin model

### LINKED ISSUE #89: Add test cases for admin model
The `Admin` model is missing test cases for:

- [x] isSameAdmin

- [x] equals

### LINKED ISSUE #90: Add test cases for Salary field
The `Salary` field is missing the following test cases:

- [x] constructor_null_throwsNullPointerException

- [x] constructor_invalidSalary_throwsIllegalArgumentException

- [x] isValidSalary

### LINKED ISSUE #91: Add test cases for the EmployDate field
The `EmployDate` field is missing the following test cases:

- [x] constructor_null_throwsNullPointerException

- [x] constructor_invalidEmployDate_throwsIllegalArgumentException

- [x] isValidEmployDate

### LINKED ISSUE #94: Add test cases for ParserUtil.java
New Parser have been added and thus require test cases

The following parser requires test cases:

- [x] ParseSalary

- [x] ParseEmployDate

- [x] ParseUsername

- [x] ParsePathToProfilePic

### LINKED ISSUE #95: Add test cases for AddAdminCommandParser
AddAdminCommandParser is missing the following test cases:

- [x] parse_compulsoryFieldMissing_failure

- [x] parse_invalidValue_failure

- [ ] parse_allFieldsPresent_success

### LINKED ISSUE #105: Add test cases for AddModuleToDatabaseCommand
`AddModuleToDatabaseCommand` is missing the following test case:

- [x] constructor_nullModule_throwsNullPointerException

- [x] notAdmin_throwsCommandException

- [x] execute_moduleAcceptedByModel_addSuccessful

- [x] execute_duplicateModule_throwsCommandException

- [x] equals

### LINKED ISSUE #107: Add test cases for AddModuleToDatabaseParser
AddModuleToDatabaseParser is missing the following test cases:

- [ ] parse_compulsoryFieldMissing_failure

### LINKED ISSUE #109: Add test cases for PathToProfilePic
The `PathToProfilePic` class is missing the following test cases:

- [ ] constructor_null_throwsNullPointerException

- [ ] constructor_invalidPathToProfilePic_throwsIllegalArgumentException

- [ ] isValidPathToProfilePic

### PR DESCRIPTION
**Pull request by deming16**
The following is the summary of milestone for midv1.2. In this PR, the add module to database command has been implemented. The `AddModuleToDatabaseCommand` allows administrators to add newly introduced modules into the database from within the application.

**Logic**

- `AddModuleToDatabaseCommand` & `AddModuleToDatabaseCommandParser` has been included. executing the command with the correct arguments would create a new `Module` and save it into `ModuleList.xml`.

**Model**

- Model Manager is also equipped with `addModuleToDatabase` method to facilitate the execution of the command and `indicateModuleListChanged` method to trigger the saving of modules to database.

**Testing**

In this PR, test cases has been created for the following classes:
`Admin`
`Salary`
`EmployDate`
`PathToProfilePic`
`AddAdminCommandParser`
`AddModuleToDatabaseCommand`
`AddModuleToDatabaseCommandParser`

Test cases have also been added for the following classes:
`ParserUtil`

Hence, this PR will resolve the following issues:
resolves #89 Add test cases for admin model
resolves #90 Add test cases for Salary field
resolves #91 Add test cases for the EmployDate field
resolves #94 Add test cases for ParserUtil.java
resolves #95 Add test cases for AddAdminCommandParser
resolves #105 Add test cases for AddModuleToDatabase
resolves #107 Add test cases for AddModuleToDatabaseParser
resolves #109 Add test cases for PathToProfilePic

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/AddAdminCommandParser.java [hunk 1]
```diff
@@ -31,29 +36,31 @@ public AddAdminCommand parse(String args) throws ParseException {
...
+        PathToProfilePic pathToProfilePic =
+                ParserUtil.parsePathToProfilePic(argMultimap.getValue(PREFIX_PATH_TO_PIC).get());
+        Salary salary = ParserUtil.parseSalary(argMultimap.getValue(PREFIX_SALARY).get());
+        EmployDate employmentDate = ParserUtil.parseEmployDate(argMultimap.getValue(PREFIX_EMPLOYMENT_DATE).get());
         Admin admin = new Admin(username, name, role, pathToProfilePic, salary,
             employmentDate);
 
 
 
         //TODO key to be replaced
```
Comment (etjk) [inline src/main/java/seedu/address/logic/parser/AddAdminCommandParser.java]: Is this comment still required?

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 2]
```diff
@@ -121,4 +126,64 @@ public static Tag parseTag(String tag) throws ParseException {
...
+        return new Salary(trimmedSalary);
+    }
+
+    /**
+     * Parses a {@code String employDate} into an {@code EmployDate}.
+     * Leading and trailing whitespaces will be trimmed.
+     *
+     * @throws ParseException if the given {@code employDate} is invalid.
+     */
+    public static EmployDate parseEmployDate(String emplyDate) throws ParseException {
```
Comment (etjk) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java]: Possible typo for `employDate`?

File: src/main/java/seedu/address/model/user/PathToProfilePic.java [hunk 3]
```diff
@@ -0,0 +1,52 @@
...
+        this.path = path;
+    }
+    /**
+     * Returns true if a given string is a valid path name.
+     */
+    public static boolean isValidPath(String test) {
+        return test.matches(PATH_VALIDATION_REGEX);
+    }
+
+
```
Comment (etjk) [inline src/main/java/seedu/address/model/user/PathToProfilePic.java]: Extra new line

File: src/main/java/seedu/address/logic/parser/AddAdminCommandParser.java (hunk 1 above)
Comment (deming16) [reply src/main/java/seedu/address/logic/parser/AddAdminCommandParser.java]: Not anymore, since key will be the same as password. It has been removed in the latest commit.

File: src/main/java/seedu/address/logic/parser/AddModuleToDatabaseCommandParser.java [hunk 4]
```diff
@@ -0,0 +1,76 @@
...
+    }
+
+    private static boolean arePrefixesPresent(ArgumentMultimap argumentMultimap, Prefix... prefixes) {
+        return Stream.of(prefixes).allMatch(prefix -> argumentMultimap.getValue(prefix).isPresent());
+    }
+
+    /**
+     * Converts the given string of available sems into booleans.
+     * @param sem
+     * @return
```
[the remark this answers is not in the document]
Comment (deming16) [reply src/main/java/seedu/address/logic/parser/AddModuleToDatabaseCommandParser.java]: Java docs updated in latest commit.

File: src/main/java/seedu/address/logic/parser/ParserUtil.java (hunk 2 above)
Comment (deming16) [reply src/main/java/seedu/address/logic/parser/ParserUtil.java]: `emplyDate` is indeed a typo. It has been corrected to `employDate` in the lastest commit.
